session_name: 'pullnix'
windows:
- window_name: bash
  focus: 'true'
  layout: bb9c,225x76,0,0[225x57,0,0,0,225x18,0,58,2]
  options: {}
  panes:
  - 
  - focus: 'true'
  start_directory: /home/joseph/projects/pullnix
